import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/contact'
import Header from '../components/header'
import styles from '../styles/Home.module.css'

import quadro1 from '../public/img/illustrations/quadro1.png'
import quadro2 from '../public/img/illustrations/quadro2.png'
import quadro3 from '../public/img/illustrations/quadro3.png'
import Footer from '../components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className={styles.main}>
        <div className={styles.mainImage}>
          <Image src={quadro1} placeholder="blur" width={300} height={500} layout="fixed" objectFit="cover" />
        </div>
        <div className={styles.mainImage}>
          <Image src={quadro2} placeholder="blur" width={300} height={500} layout="fixed" objectFit="cover" />
        </div>
        <div className={styles.mainImage}>
          <Image src={quadro3} placeholder="blur" width={300} height={500} layout="fixed" objectFit="cover" />
        </div>
      </main>

      <Contact />
      <Footer />
    </>
  )
}
